name: Build and publish
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  build:
    needs: [tests]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Caprine
        run: npm run build
      - name: Package Caprine for macOS
        if: startsWith(matrix.os, 'macos')
        run: npm run dist:mac -- --publish always
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package Caprine for Windows
        if: startsWith(matrix.os, 'windows')
        run: npm run dist:win -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package Caprine for Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: npm run dist:linux -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
